name: Test action from repository

on: [push, release]

jobs:
  get_draft:
    name: "Get draft release from all releases"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "call action"
        id: last_release
        uses: ./
        with:
          token: ${{ github.token }}
          excludes: "release"
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
          echo "release: ${{ steps.last_release.outputs.release }}"
          echo "upload_url: ${{ steps.last_release.outputs.upload_url }}"
      - name: "Assert"
        run: |
          if [[ "${{ steps.last_release.outputs.id }}" == "" ]];
          then
            echo "Wrong release ID"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.draft }}" != "true" ]];
          then
            echo "Release is NOT in draft"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.prerelease }}" != "false" ]];
          then
            echo "It is a prerelease"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.release }}" != "false" ]];
          then
            echo "It is Prod Release"
            exit 4
          fi

  get_prerelease:
    name: "Get prerelease release from all releases"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "call action"
        id: last_release
        uses: ./
        with:
          token: ${{ github.token }}
          excludes: "draft,release"
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
          echo "upload_url: ${{ steps.last_release.outputs.upload_url }}"
      - name: "Assert"
        run: |
          if [[ "${{ steps.last_release.outputs.id }}" == "" ]];
          then
            echo "Wrong release ID"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.draft }}" == "true" ]];
          then
            echo "Release is draft"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.prerelease }}" != "true" ]];
          then
            echo "It is NOT a prerelease"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.release }}" != "false" ]];
          then
            echo "It is Prod Release"
            exit 4
          fi

  get_release:
    name: "Get release release from all releases"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "call action"
        id: last_release
        uses: ./
        with:
          token: ${{ github.token }}
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
          echo "upload_url: ${{ steps.last_release.outputs.upload_url }}"
      - name: "Assert"
        run: |
          if [[ "${{ steps.last_release.outputs.id }}" == "" ]];
            then
              echo "Wrong release ID"
              exit 4
            fi
            if [[ "${{ steps.last_release.outputs.draft }}" == "true" ]];
            then
              echo "Release is draft"
              exit 4
            fi
            if [[ "${{ steps.last_release.outputs.prerelease }}" == "true" ]];
            then
              echo "It is a prerelease"
              exit 4
            fi
            if [[ "${{ steps.last_release.outputs.release }}" != "true" ]];
            then
              echo "It is Prod Release"
              exit 4
            fi

  get_zero_because_of_top_list_limit:
    name: "Get no release because draft is canceled and limit is set to 1"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "call action"
        id: last_release
        uses: ./
        with:
          token: ${{ github.token }}
          excludes: "release"
          view_top: 1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
          echo "upload_url: ${{ steps.last_release.outputs.upload_url }}"
      - name: "Assert"
        run: |
          if [[ "${{ steps.last_release.outputs.id }}" != "" ]];
          then
            echo "Wrong release type"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.draft }}" != "" ]];
          then
            echo "Wrong release type"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.prerelease }}" != "" ]];
          then
            echo "Wrong release type"
            exit 4
          fi
          if [[ "${{ steps.last_release.outputs.release }}" != "" ]];
          then
            echo "Wrong release type"
            exit 4
          fi
